// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "page-title": "Veterinary Home Visits in Stockholm - Professional Care at Home for Dogs, Cats & Rabbits.",
    "page-description": "Book a home visit from an experienced vet in the Greater Stockholm area. We offer professional and convenient care in your home - for dogs, cats and rabbits who deserve the very best."
  },
  "Navigation": {
    "services": "Veterinary services",
    "home-visit": "Home visit",
    "prices": "Prices",
    "advices": "Tips & Advice",
    "book": "Book appointment"
  },
  "Logo": {
    "aria-link-homepage": "Home page."
  }
};
export default messages;