// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "page-title": "This is Home page.",
    "page-description": "This is Home page description."
  }
};
export default messages;